import { records as legacyRecords, taxonomy, labels } from './data.js';
import { records as phase4Records0 } from './data-phase4-0436-0460.js';
import { records as phase4Records1 } from './data-phase4-0461-0485.js';
import { records as phase4Records2 } from './data-phase4-0486-0510.js';
import { records as phase4Records3 } from './data-phase4-0511-0535.js';
import { records as phase4Records4 } from './data-phase4-0536-0560.js';
import { records as phase4Records5 } from './data-phase4-0561-0585.js';
import { records as phase4Records6 } from './data-phase4-0586-0610.js';
import { records as phase4Records7 } from './data-phase4-0611-0635.js';
export const records = [...legacyRecords, ...phase4Records0, ...phase4Records1, ...phase4Records2, ...phase4Records3, ...phase4Records4, ...phase4Records5, ...phase4Records6, ...phase4Records7];
export { taxonomy, labels };
export { byId, search } from './catalog.js';
export { composeProject, estimateAutomation, visibleQuestions } from './engine.js';
export { validateCatalog } from './validate.js';
